<a href="https://colab.research.google.com/github/Adyypower/Deep-learning-Models-or-topics/blob/main/1_tokenizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from transformers import BertModel , AutoTokenizer
import pandas as pd

In [3]:
model_name = 'bert-base-cased'
model = BertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [4]:
sentence = "When life gives you lemons, don`t make lemonad"
tokens = tokenizer.tokenize(sentence)
print(tokens)

['When', 'life', 'gives', 'you', 'lemon', '##s', ',', 'don', '`', 't', 'make', 'lemon', '##ad']

In [6]:
vocab = tokenizer.vocab
vocab

{'seldom': 17336,
 'enclosed': 10949,
 'Germany': 1860,
 'ン': 973,
 'Dave': 4111,
 '##HA': 11612,
 'ъ': 501,
 'maize': 26114,
 'dem': 26707,
 'theater': 5184,
 'Wolverhampton': 21900,
 '1854': 8023,
 'Nixon': 11302,
 'true': 2276,
 'Reeves': 19481,
 'pine': 10194,
 'superficial': 26558,
 '##nir': 20461,
 'dramatic': 7271,
 'file': 4956,
 'Kiel': 23144,
 'Bob': 3162,
 'Bruins': 19552,
 'ancestry': 11626,
 '##idy': 25382,
 'horizontally': 26126,
 '##（': 28990,
 'canonical': 21768,
 '##rka': 23870,
 '##dges': 25477,
 'subscription': 16759,
 'greeting': 15908,
 'fellow': 3235,
 'ha': 5871,
 '##idated': 27893,
 'tugging': 19029,
 'Monster': 11701,
 'Broadcast': 19142,
 'Pontiac': 27681,
 '##bag': 17097,
 'Reference': 19714,
 '##ility': 13378,
 'Services': 4326,
 '##О': 28379,
 'ه': 591,
 'Tang': 10215,
 'ain': 9562,
 '##ס': 28461,
 'Fox': 3977,
 'Benson': 12093,
 'just': 1198,
 'toilet': 12356,
 'Kingdoms': 25316,
 'Maximum': 13878,
 'utter': 15462,
 'estimate': 10301,
 '##rō': 19651,
 'Matters': 26764,
 '##sponsible': 26408,
 '##nberg': 8904,
 'Daddy': 9979,
 '##bloid': 27109,
 '##lins': 17828,
 'removal': 8116,
 'inflammatory': 22653,
 'vegetable': 17690,
 'fore': 24387,
 'colours': 9849,
 'timetable': 27646,
 'Venus': 11968,
 'strategy': 5564,
 'narrow': 4142,
 '1983': 2278,
 'য': 656,
 'consisted': 4227,
 'Roe': 26301,
 '##ughter': 26760,
 'Association': 1791,
 'Gong': 23703,
 'survives': 14134,
 '##vision': 12959,
 'brains': 16570,
 'spectral': 20277,
 'applying': 11892,
 'Julio': 16786,
 'Administration': 4918,
 'Hidden': 19595,
 '##ental': 22692,
 '##â': 28198,
 '##fields': 14922,
 'masters': 11573,
 '##rdy': 21366,
 'Still': 4209,
 'dig': 11902,
 '##sper': 20623,
 'trash': 13151,
 'grim': 14816,
 'unopposed': 18508,
 'Steelers': 16060,
 '##ᵒ': 28619,
 'polynomial': 19068,
 '252': 25479,
 'surge': 12814,
 'Promise': 18432,
 'suicide': 5680,
 '##sler': 21318,
 '##iga': 13499,
 '##ain': 8104,
 '##ifer': 25052,
 'Diamonds': 24900,
 '##¼': 28176,
 'secretly': 10173,
 '##ỳ': 28668,
 'readers': 8460,
 '##eca': 25534,
 'warriors': 9171,
 'Cain': 11753,
 'roadway': 20722,
 'Ice': 6172,
 'league': 2074,
 'halted': 12919,
 'towed': 20965,
 'entries': 10813,
 'cannon': 12136,
 'Augsburg': 27398,
 'mob': 13221,
 'votes': 3667,
 'illustrations': 11880,
 'McDonald': 9092,
 'Bar': 6523,
 '##л': 28400,
 '##del': 6738,
 'barony': 26488,
 'Restoration': 15988,
 'circuit': 6090,
 'Staten': 27188,
 'sped': 18132,
 'packet': 17745,
 'teenager': 10674,
 'facilitate': 11000,
 'rating': 5261,
 'signed': 1878,
 'Perhaps': 5203,
 'envy': 26867,
 'spelled': 11517,
 'humanity': 9011,
 '[unused42]': 42,
 'scenic': 18307,
 'sustaining': 26081,
 '##⁴': 28704,
 '##isch': 16253,
 'See': 3969,
 'produce': 3133,
 '£': 202,
 'Theological': 14029,
 '##ät': 27888,
 '##zhi': 23239,
 'candle': 15488,
 'surgery': 6059,
 'pin': 10473,
 '19th': 2835,
 '²': 213,
 'dominating': 24778,
 'producing': 4411,
 'bacterial': 19560,
 'zipper': 26074,
 'Harper': 8135,
 'com': 3254,
 'Europe': 1980,
 'Lucian': 19618,
 'reduction': 7234,
 'al': 2393,
 '##wart': 18320,
 'comprise': 16722,
 'gap': 7275,
 'stinging': 25648,
 'Gettysburg': 25117,
 'Masovian': 26506,
 'Happy': 8325,
 'advisory': 13372,
 'Basilica': 19349,
 '##vert': 12986,
 'Angel': 5876,
 '##TM': 19974,
 'extraordinary': 10264,
 'stationary': 19255,
 'rabbits': 25164,
 'Sur': 17078,
 'assessed': 14758,
 'copper': 7335,
 'overview': 24431,
 'u': 190,
 'snarled': 15742,
 '2007': 1384,
 'eagle': 13387,
 'Resort': 15579,
 '##par': 17482,
 '##iology': 17288,
 'frontman': 25063,
 '`': 169,
 '##∗': 28746,
 'ா': 679,
 'sudden': 4962,
 'None': 7330,
 'versus': 6055,
 '##ropic': 27098,
 'Willis': 12886,
 'Liz': 8719,
 'escaping': 13755,
 'executed': 5858,
 'hurts': 15483,
 'closed': 1804,
 'privacy': 9909,
 'packed': 8733,
 '160': 7690,
 'vest': 21531,
 'Satellite': 16827,
 '₱': 837,
 'mist': 12791,
 '##iques': 18853,
 'Draw': 22877,
 'issue': 2486,
 'Reuben': 18522,
 'convened': 21419,
 'Trojan': 28099,
 '##cona': 26639,
 'Painter': 15502,
 '##vention': 21987,
 'crossed': 3809,
 'windows': 3751,
 'somehow': 5006,
 'metal': 2720,
 'Sylvester': 21855,
 't': 189,
 'renewed': 8978,
 'walking': 3179,
 '##ms': 4206,
 '##room': 6077,
 'terrorism': 12010,
 'intensive': 12885,
 '##uding': 21705,
 'shut': 3210,
 'throbbing': 18767,
 'Kuwait': 13397,
 '4th': 3492,
 'obeyed': 25314,
 'culminating': 18174,
 'advancing': 11120,
 'Creek': 3063,
 'initiate': 19687,
 'fingernails': 23654,
 '##islav': 23012,
 'Retired': 14454,
 'betting': 21891,
 'hospitality': 21604,
 '##nosis': 27078,
 'raked': 24962,
 'Proceedings': 20661,
 'Moving': 13091,
 'office': 1701,
 'archaeologists': 24104,
 '345': 26625,
 'calculating': 23172,
 '##ytic': 23894,
 'Wagner': 10171,
 'certificate': 10890,
 'Desert': 9054,
 'investigator': 17805,
 '##scope': 15300,
 '##anu': 19762,
 '##eto': 20713,
 'Petit': 21386,
 'vaguely': 16559,
 '##cell': 22494,
 'Thai': 6888,
 'Wells': 7909,
 '##çaise': 20952,
 'grunted': 15637,
 '##do': 2572,
 'deliberately': 9938,
 '##rick': 8053,
 'eighteen': 8105,
 '##odies': 25258,
 'rumble': 24102,
 'Lucky': 8034,
 '##tta': 5100,
 'Barlow': 19124,
 '##ک': 28503,
 '##rda': 18484,
 'books': 2146,
 'Duff': 23719,
 'clinging': 19728,
 'knowledge': 3044,
 'Districts': 18803,
 'plane': 4261,
 'Marta': 22930,
 '##mpo': 24729,
 'ₓ': 827,
 'Cinematography': 27062,
 'Lawrence': 4898,
 'Citation': 17028,
 '##abe': 22377,
 'mesh': 24000,
 'quantitative': 25220,
 'wrapping': 13261,
 'lacks': 14756,
 'Hits': 12852,
 '##ndo': 13645,
 'Iris': 13476,
 'Cottage': 20948,
 'ranch': 10804,
 'Boris': 11265,
 '##ं': 28508,
 'immense': 14934,
 'comedies': 25795,
 'Bryant': 12637,
 '##\\': 28148,
 '##dre': 11114,
 '##ride': 17731,
 '##unch': 14480,
 'soon': 1770,
 'skilled': 10715,
 'designers': 12297,
 'track': 1854,
 'Weber': 13718,
 'bowed': 11543,
 'opponents': 7741,
 'progression': 16147,
 'carriers': 11837,
 'grazing': 16747,
 'ὰ': 772,
 'Ş': 320,
 '##coe': 16123,
 'collaborators': 24146,
 '##mba': 10806,
 'gable': 16254,
 'Judd': 21971,
 'knocking': 10760,
 'grouped': 15965,
 'Serra': 25605,
 'Funding': 24811,
 'shoreline': 20953,
 'Bundesliga': 14814,
 'chill': 11824,
 'vomit': 26979,
 'genocide': 19643,
 'mercenaries': 22222,
 'Rae': 16345,
 'proximity': 10013,
 '1794': 13506,
 'Miguel': 7975,
 'teaches': 12209,
 'fuck': 9367,
 'Submarine': 26399,
 '##cu': 10182,
 'cutting': 5910,
 'scattered': 7648,
 '##宮': 28910,
 '‒': 781,
 'dancers': 11314,
 '##unted': 13153,
 'Pradesh': 7530,
 'emissions': 12349,
 'hills': 7000,
 'counts': 10664,
 'ambassador': 9088,
 'Legion': 8890,
 '227': 23689,
 '##rly': 25339,
 'lions': 20050,
 'stumble': 24545,
 'spectrum': 10122,
 'Seal': 19200,
 'operate': 4732,
 '##russ': 25357,
 '##pice': 15633,
 '##ān': 20208,
 'spherical': 21279,
 'While': 1799,
 'Original': 7267,
 'notice': 4430,
 'minimum': 5867,
 '##vity': 14499,
 '##tom': 18778,
 '##rle': 15576,
 'Stevens': 8437,
 'Deacon': 23452,
 'oversized': 24223,
 'instruction': 8235,
 'Ali': 4149,
 'Eclipse': 22301,
 'impressive': 7757,
 '[unused94]': 94,
 'Haiti': 13364,
 'Fate': 17711,
 '##duct': 13890,
 'establishes': 23497,
 'cheeks': 5388,
 'wake': 5314,
 'serviced': 25658,
 'grabbing': 10810,
 'assistant': 3109,
 'sedan': 19170,
 'locally': 6889,
 '##field': 2427,
 'licence': 12155,
 'Kaiser': 16692,
 'candidates': 4765,
 'Packard': 27065,
 'var': 15661,
 'infectious': 20342,
 'Guard': 4813,
 '##π': 28352,
 'Reilly': 14347,
 '##asing': 17764,
 '##umes': 25965,
 'nationalism': 16767,
 '##craft': 8444,
 '##aria': 11315,
 'rights': 2266,
 'cartridge': 16542,
 'whatsoever': 20748,
 'Trail': 6938,
 'additional': 2509,
 'Banks': 10117,
 'indie': 12665,
 'Rudolf': 12995,
 'ISSN': 26273,
 '##O': 2346,
 'Dock': 20115,
 '##ilitating': 26039,
 '##rail': 12797,
 'adventures': 12108,
 'receptions': 17753,
 'Pack': 14667,
 'partial': 7597,
 'neighbouring': 9586,
 'urge': 8869,
 'institutions': 4300,
 'closer': 2739,
 'Rod': 11945,
 'album': 1312,
 'charities': 18844,
 'holders': 14322,
 'bricks': 15453,
 'oversee': 18800,
 '##abulous': 20356,
 '##国': 28897,
 '69': 5691,
 'sells': 16695,
 '##brush': 20248,
 'recounts': 26214,
 'te': 21359,
 'characteristics': 5924,
 '##ly': 1193,
 'Nazi': 5755,
 'Ari': 10789,
 '##heimer': 19263,
 'assembled': 8968,
 'includes': 2075,
 'm²': 6450,
 'Orchestra': 4590,
 '##alis': 14200,
 'ʿ': 383,
 '103': 9550,
 'kicker': 27219,
 'once': 1517,
 'Isa': 27334,
 'SF': 18659,
 'integration': 9111,
 '##end': 6696,
 'goals': 2513,
 'Going': 11099,
 'draft': 5039,
 'Mellon': 24587,
 'provisional': 16750,
 'coughed': 20720,
 '##asis': 14229,
 'Ministry': 3424,
 '##rance': 10555,
 '##chan': 18546,
 '##sity': 13730,
 'Rodrigo': 20551,
 'surveyed': 13186,
 'wider': 6815,
 'tunic': 25852,
 'Pet': 25993,
 'divide': 13330,
 'Cable': 15038,
 'September': 1347,
 '##ừ': 28664,
 '##pository': 24454,
 'Blair': 10378,
 '##Ј': 28365,
 'commemorative': 22180,
 'thrust': 7113,
 'Despite': 2711,
 '##С': 28382,
 '09': 4925,
 'Wan': 17878,
 '##rative': 15306,
 'feast': 11995,
 'tensions': 14696,
 'participants': 6635,
 '##bodied': 27991,
 '##ipur': 26164,
 '##az': 10961,
 'Galerie': 19851,
 'recognizing': 17344,
 'delivered': 4653,
 '##cale': 20532,
 'bats': 13534,
 'beer': 5298,
 '##al': 1348,
 'missile': 8233,
 'Calder': 21056,
 '##itch': 18963,
 'Ad': 24930,
 'crowds': 13484,
 '##gara': 17582,
 '##quence': 25113,
 'revival': 9408,
 'cotton': 7825,
 'tiles': 13947,
 '##ious': 4179,
 '##apon': 26655,
 'ù': 271,
 'choices': 9940,
 'Welch': 19370,
 '##nant': 14618,
 'array': 9245,
 'marked': 3597,
 'avid': 21976,
 'armament': 18829,
 'notable': 3385,
 '##स': 28529,
 '##ermined': 26486,
 'Chinatown': 24812,
 'ache': 12953,
 '##bba': 27261,
 'fetch': 21616,
 'content': 3438,
 '##DP': 13339,
 'Ames': 22501,
 'interpretations': 17555,
 'Alma': 15717,
 'fury': 10842,
 'Nor': 16162,
 '##dad': 14810,
 'Put': 11913,
 '##ires': 22758,
 'Boat': 12936,
 'Sato': 26824,
 'Extended': 19757,
 '##rano': 23367,
 'Thought': 15255,
 'distributions': 23190,
 'quasi': 21711,
 'serve': 2867,
 'Thor': 16261,
 'blocks': 5511,
 '##ardt': 25018,
 'Jan': 4945,
 '##rg': 10805,
 '。': 886,
 'markings': 14655,
 'Ava': 11651,
 'homeless': 12501,
 '##ved': 5790,
 'considering': 6103,
 'Pasadena': 20458,
 'fumble': 21577,
 '##rook': 18562,
 'Princeton': 8845,
 'monopoly': 18356,
 'Fort': 3144,
 '##¡': 28157,
 'acceleration': 18383,
 'Montevideo': 24942,
 'Andes': 19505,
 'rapper': 11333,
 'considered': 1737,
 '##tured': 23132,
 '##inate': 14248,
 'guides': 15889,
 '##hogany': 26724,
 'operation': 2805,
 'β': 419,
 'pipes': 13655,
 'WA': 22751,
 '##cession': 16122,
 'registered': 4410,
 'Katherine': 9179,
 '##erman': 14170,
 '##ceptive': 17046,
 'DSO': 25577,
 'Weight': 25589,
 'Malta': 9723,
 '##lles': 12132,
 '##ally': 2716,
 'volatile': 23332,
 'Household': 25705,
 'wavy': 26985,
 'harsh': 8213,
 'disabled': 10302,
 'yeah': 8147,
 'moniker': 24395,
 '##と': 28805,
 '##runner': 14627,
 'shrink': 26406,
 'tremendous': 15194,
 'Barton': 13235,
 'tournament': 2348,
 'tighten': 23847,
 'digging': 10750,
 'Excuse': 20676,
 'monthly': 7868,
 '##rya': 20845,
 'localized': 25813,
 'stimulate': 26225,
 'concentrated': 7902,
 'used': 1215,
 '〜': 893,
 '##nne': 10934,
 'steady': 6386,
 '##ID': 9949,
 '##ě': 28222,
 'pictured': 17066,
 'Amsterdam': 7101,
 'Ain': 12088,
 'Standards': 14365,
 'strokes': 15007,
 'considerable': 5602,
 'city': 1331,
 '[unused55]': 55,
 'cavern': 19373,
 '##uns': 17096,
 'Robbins': 19462,
 '##und': 6775,
 'los': 12724,
 'fungi': 17005,
 '£2': 24155,
 '##destine': 27543,
 'glowed': 17531,
 'moon': 5907,
 '##川': 28916,
 'Oman': 17739,
 'kidding': 12873,
 '##cre': 13782,
 'Including': 25951,
 'Why': 2009,
 'adolescent': 25506,
 'engaged': 4349,
 'Bay': 2410,
 'formal': 4698,
 '211': 20915,
 '##sities': 28060,
 'captivity': 17737,
 'invested': 11285,
 '##ʀ': 28286,
 'possesses': 15614,
 'region': 1805,
 'financed': 14395,
 'Houses': 16862,
 '##chy': 8992,
 'physicist': 14646,
 'geographically': 26160,
 'posture': 18229,
 '##toria': 14155,
 'Roberto': 10599,
 'supernatural': 12361,
 'Chart': 6900,
 '##culture': 19695,
 'star': 2851,
 'Colombian': 13977,
 'Alzheimer': 24278,
 'Beaver': 16626,
 '##OW': 17056,
 'panties': 12351,
 'Paper': 11594,
 'couldn': 1577,
 'BWF': 23342,
 'Square': 4656,
 'causing': 3989,
 '##et': 2105,
 'flatly': 27337,
 'Stanford': 8036,
 'shaken': 18673,
 'Asia': 3165,
 'angled': 20423,
 'Chandra': 17595,
 'Roses': 17303,
 'merged': 4564,
 '##ῶ': 28680,
 'br': 9304,
 'communications': 6678,
 '##tip': 27961,
 '##₆': 28713,
 '##omo': 18445,
 'Scientology': 26973,
 '26': 1744,
 '##via': 7137,
 'Infantry': 4155,
 'Cathedral': 5761,
 'upper': 3105,
 'Hate': 20735,
 'steals': 16867,
 'Wow': 11750,
 'disabilities': 16292,
 '##lad': 23850,
 'strengthening': 18185,
 '##ager': 12344,
 '##chism': 25564,
 '##rot': 10595,
 'Abbott': 15176,
 '40th': 17583,
 '##rada': 22077,
 '##ộ': 28657,
 '##urous': 25576,
 'Micro': 27730,
 'Minh': 21481,
 '##mir': 15191,
 'sewage': 23198,
 'Scientific': 8787,
 'א': 535,
 '##ogged': 24009,
 'ideological': 19800,
 '##中': 28873,
 '##cure': 22712,
 '2006': 1386,
 'Mt': 13086,
 '##scribed': 25626,
 'passports': 23047,
 'diocese': 9856,
 'Tate': 9727,
 '##ringing': 27812,
 'Bend': 15913,
 'Archive': 15041,
 'columnist': 14219,
 'Francis': 3720,
 'board': 2313,
 'Bury': 19390,
 'Bedford': 12094,
 '322': 26605,
 'paradise': 23876,
 'plausible': 27918,
 '1823': 12683,
 'Friend': 13058,
 '##nson': 15703,
 '##מ': 28458,
 'atmosphere': 6814,
 'Once': 2857,
 '##wirl': 26137,
 'Now': 1986,
 '##ggy': 14720,
 'resting': 8137,
 'Vlad': 20868,
 'Daughters': 24645,
 'prestigious': 8593,
 'prefers': 21042,
 'Prince': 2558,
 '##holm': 20798,
 '##iciency': 23864,
 'ʻ': 380,
 'ᶜ': 724,
 'Woodward': 20825,
 '##ulter': 27367,
 'Erica': 21205,
 '##ae': 5024,
 'okay': 3008,
 'chronicle': 26539,
 '##ffling': 20709,
 'Instituto': 25218,
 'groan': 13344,
 'toss': 10234,
 'award': 2574,
 'initials': 22563,
 'adviser': 14269,
 'accusing': 18001,
 '1774': 18838,
 '##weed': 14315,
 '##wave': 17159,
 'understands': 21744,
 'Beijing': 6671,
 '##lio': 9436,
 'anytime': 20166,
 '##far': 14794,
 '1991': 1984,
 'Fowler': 15738,
 '##egation': 24097,
 'follows': 3226,
 'Bourbon': 19247,
 'Blake': 5887,
 'response': 2593,
 'Godfrey': 19635,
 'efficiently': 19723,
 'Kylie': 8647,
 'degrees': 4842,
 'Chrysler': 18991,
 'attractive': 8394,
 'investigation': 4449,
 '##oly': 23415,
 'Peters': 12648,
 'Talk': 8768,
 'ancestor': 13596,
 'attends': 27150,
 '##lang': 19514,
 'assaults': 25720,
 'aids': 23078,
 'Joanna': 16934,
 'baking': 26377,
 'blur': 17283,
 'motorcycles': 21552,
 'Hunter': 4242,
 'tales': 11297,
 'Hot': 4126,
 'everyone': 2490,
 'Boyle': 17846,
 'paste': 24854,
 '天': 1010,
 '##as': 2225,
 'achieve': 5515,
 'Stafford': 15785,
 '##ἐ': 28671,
 'Josie': 16169,
 '##top': 9870,
 'Pieter': 26609,
 'hemisphere': 24114,
 '##ical': 4571,
 'implications': 14755,
 'frowned': 6804,
 'ineligible': 25311,
 'Christophe': 26921,
 '##rek': 14909,
 'Emmy': 9933,
 'Donnell': 19412,
 '##mmy': 16211,
 'Grande': 9109,
 '275': 18783,
 'spider': 12545,
 'reviewed': 7815,
 'wages': 13588,
 'Cade': 20426,
 'remarkable': 9495,
 '##hall': 8897,
 '##una': 9291,
 'insist': 19831,
 'smaller': 2964,
 'professionals': 8799,
 'touched': 4270,
 '##nale': 25668,
 'unarmed': 26809,
 'Collection': 6712,
 'Currie': 22642,
 'gripping': 15436,
 'pseudo': 23563,
 'fortified': 14149,
 'Cope': 26673,
 '##lut': 25937,
 'accuracy': 10893,
 '2013': 1381,
 'Harvest': 23119,
 'Depression': 11442,
 'Kids': 9904,
 'Outside': 9572,
 'depression': 7560,
 'horrified': 16161,
 'Words': 13212,
 'Mercy': 14130,
 'reluctant': 12061,
 'Chang': 11497,
 'Greg': 6155,
 'transports': 21951,
 'cadet': 22602,
 'nothing': 1720,
 'Mai': 17551,
 '##gat': 25524,
 'instant': 6879,
 'survivor': 17544,
 'criterion': 26440,
 'Sandra': 13114,
 'summon': 21147,
 'э': 504,
 'Eliot': 17324,
 'curled': 7787,
 'Survey': 8157,
 'con': 14255,
 '1819': 12720,
 'humans': 3612,
 'Nassau': 15272,
 '##sle': 27112,
 'motor': 5968,
 'quickly': 1976,
 'proposal': 5835,
 'evolve': 23530,
 'master': 3283,
 '[unused52]': 52,
 'gains': 12535,
 'Isabel': 11726,
 '##Č': 28215,
 'Twice': 24715,
 '201': 17365,
 '52': 3882,
 'pier': 16331,
 'Skills': 26210,
 'Gang': 12469,
 'mayor': 4398,
 'w': 192,
 'reads': 9568,
 '##rieve': 27055,
 'taught': 3188,
 'attained': 12961,
 'Zagreb': 13203,
 'Minor': 8187,
 'graves': 14489,
 '##bark': 24063,
 'Prison': 11375,
 'pale': 4554,
 'habitat': 6296,
 'dining': 7659,
 'tracked': 13183,
 '##ération': 27686,
 '##pruce': 21641,
 'neural': 18250,
 'Waste': 27124,
 'accomplished': 8587,
 'blackish': 24534,
 'Slow': 19826,
 'tender': 8886,
 '137': 15679,
 'playwright': 11617,
 'preventing': 10878,
 'vampire': 3980,
 '##lmer': 23370,
 'ш': 499,
 'Dr': 1987,
 'find': 1525,
 '##imed': 24733,
 'mating': 16982,
 'wonders': 21346,
 'think': 1341,
 '##ն': 28431,
 'Assistance': 20778,
 '226': 23100,
 'jealous': 10282,
 'drainage': 12779,
 '##車': 28965,
 'excellent': 6548,
 'compressed': 18273,
 'Akira': 23980,
 'sanctioned': 15572,
 '##mo': 3702,
 'log': 9366,
 'Test': 5960,
 '##steries': 24748,
 '##sar': 9724,
 'predominantly': 8941,
 'projecting': 20266,
 'section': 2237,
 'Terry': 6050,
 'tier': 8081,
 '■': 871,
 'diversity': 9531,
 'exclusively': 7097,
 '##itt': 9642,
 'י': 544,
 'Monte': 10046,
 'defendants': 18047,
 'transplant': 26965,
 'skull': 7753,
 'exhibition': 4627,
 'tombs': 19627,
 'combines': 14215,
 'absence': 5884,
 'oxidation': 22256,
 'various': 1672,
 'difficulties': 7866,
 'extracted': 16939,
 '121': 12794,
 'packaged': 24946,
 'freedom': 4438,
 'strengthened': 14544,
 'heir': 8048,
 '##ᵥ': 28625,
 'Dynamo': 19725,
 '##hm': 18208,
 'poverty': 5224,
 '##gated': 10901,
 'Applied': 12547,
 'Alexia': 24080,
 'Wehrmacht': 26165,
 'Rough': 19479,
 'Indiana': 4456,
 'packs': 16777,
 '##ニ': 28849,
 'newborn': 24820,
 'devices': 5197,
 'grossing': 19842,
 'clinic': 12257,
 'Behind': 8291,
 ...}

In [7]:
vocab_df = pd.DataFrame({'token':vocab.keys() , 'id':vocab.values()})
vocab_df.head()

      token     id
0    seldom  17336
1  enclosed  10949
2   Germany   1860
3         ン    973
4      Dave   4111

In [8]:
token_id = tokenizer.encode(sentence)
token_id

[101,
 1332,
 1297,
 3114,
 1128,
 22782,
 1116,
 117,
 1274,
 169,
 189,
 1294,
 22782,
 3556,
 102]

In [9]:
len(tokens)

13

In [10]:
len(token_id)

15

In [13]:
vocab_df.iloc[101]

token      252
id       25479
Name: 101, dtype: object

In [14]:
list(zip(tokens,token_id[1:-1]))

[('When', 1332),
 ('life', 1297),
 ('gives', 3114),
 ('you', 1128),
 ('lemon', 22782),
 ('##s', 1116),
 (',', 117),
 ('don', 1274),
 ('`', 169),
 ('t', 189),
 ('make', 1294),
 ('lemon', 22782),
 ('##ad', 3556)]

In [15]:
tokenizer.decode(token_id)

'[CLS] When life gives you lemons, don ` t make lemonad [SEP]'

In [17]:
tokenizer_out = tokenizer(sentence)
tokenizer_out

{'input_ids': [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [19]:
sentence2 = sentence.replace('don`t', '')

In [21]:
tokenizer_2 = tokenizer([sentence,sentence2],padding = True)
tokenizer_2

{'input_ids': [[101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1274, 169, 189, 1294, 22782, 3556, 102], [101, 1332, 1297, 3114, 1128, 22782, 1116, 117, 1294, 22782, 3556, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]}